version: '3'

services:
  triton:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./model_repository:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8003:8003"
    volumes:
      - ./api:/app
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./stats:/app/stats
    depends_on:
      - triton
    environment:
      - TRITON_URL=http://triton:8000