FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances système
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copier seulement les requirements et les installer d'abord
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code
COPY api/ .

# Exposer le port de l'API
EXPOSE 8003

# Commande pour démarrer l'API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"]